apps/admission/filters.py
apps/admission/tests/test_views.py
apps/admission/urls.py
apps/admission/views.py

feat(LMS-247): add interviews import csv button for curators

---

apps/admission/tests/test_views.py

fix(LMS-246): fix date in test

---

apps/admission/views.py

fix(LMS-246): add interview ordering in dump

---

apps/admission/signals.py

fix(LMS-129): delete email before model deletion

---

apps/admission/services.py
apps/admission/tests/test_utils.py

fix(LMS-129): delete only corresponding interview reminder

---

apps/courses/models.py
apps/courses/tests/test_models.py
apps/learning/study/views.py
apps/users/views.py
lms/jinja2/lms/study/course_list.html
lms/jinja2/lms/user_profile/_tab_account.html

feat(LMS-298): fix another site course urls

---

apps/admission/forms.py
apps/admission/selectors.py
apps/admission/services.py
apps/admission/tests/factories.py
apps/core/tests/factories.py
compscicenter_ru/apps/application/tests.py
lms/jinja2/lms/admission/confirmation_of_acceptance.html

fix(LMS-297): use new university model

---

apps/admission/forms.py
apps/admission/models.py
apps/admission/selectors.py
apps/admission/services.py

fix(LMS-297): support for applicants with university_legacy data

---

lms/jinja2/lms/user_profile/_tab_account.html

fix(LMS-248): move field in private zone

---

apps/admission/management/commands/stage4_results.py

feat(LMS-297): mailing only for those who were at the interview

---

apps/learning/tests/test_enrollment.py

fix(LMS-279): emit signal in test

---

apps/courses/constants.py
apps/learning/models.py
lms/jinja2/lms/study/assignment_list.html
lms/jinja2/lms/study/student_assignment_detail.html
lms/jinja2/lms/teaching/assignment_detail.html
lms/jinja2/lms/teaching/student_assignment_detail.html
lms/jinja2/lms/user_profile/_tab_assignments.html

feat(LMS-292): add css_class colors for student assignment statuses

---

docker-files/app/common.Dockerfile

replace pipenv lock with pipenv requirements

---

docker-files/app/common.Dockerfile

fix pipenv argument

---

lk_yandexdataschool_ru/k8s/templates/app-env.yaml
lk_yandexdataschool_ru/k8s/templates/secrets.yaml

feat(LMS-296): change api access key and remoteRef for secret

---

apps/users/views.py
lms/jinja2/lms/user_profile/_tab_account.html

feat(LMS-306): make academic discipline visible for student on main page

---

apps/courses/models.py

feat(LMS-251): default course visibility is only for student participants

---

apps/learning/gradebook/data.py
apps/users/views.py
lms/jinja2/lms/gradebook/gradebook_form.html
lms/jinja2/lms/user_profile/_tab_account.html

feat(LMS-206): add invitation hint to profile and gradebook

---

apps/courses/permissions.py
lms/tests.py
lms/views.py

…als access for invited students

fix(LMS-251): bug fixes

---

apps/learning/admin.py
apps/learning/gradebook/forms.py
apps/learning/gradebook/services.py
apps/learning/gradebook/tests.py
apps/learning/gradebook/views.py
apps/learning/models.py
apps/learning/services/enrollment_service.py
apps/learning/settings.py
apps/learning/teaching/urls.py
apps/learning/tests/test_admin.py
apps/learning/tests/test_services.py
apps/learning/tests/test_student_groups.py
apps/staff/urls.py
lms/jinja2/lms/gradebook/_modal_import_csv_enrollments.html
lms/jinja2/lms/gradebook/_modal_import_csv_stepik.html
lms/jinja2/lms/gradebook/_modal_import_csv_yandex_login.html
lms/jinja2/lms/gradebook/gradebook_form.html

feat(LMS-187): import enrollment grades from CSV

---

lms/jinja2/lms/gradebook/_modal_import_csv_yandex_login.html

fix(LMS-261): close div tag

---

apps/templates/users/reference_shad_en_graduated_detail.html
apps/templates/users/reference_shad_en_with_courses_detail.html
apps/templates/users/reference_shad_ru_with_courses_detail.html
apps/templates/users/reference_shad_ru_without_courses_detail.html
apps/users/tests/test_certificates_of_participation.py
apps/users/views.py

feat(LMS-291): student reference page update image logos and add print button

---

apps/learning/study/tests/test_misc.py
apps/learning/study/views.py
lms/jinja2/lms/study/assignment_list.html

fix(LMS-307): hide inactive student assignments from unenrolled course

---

apps/templates/users/reference_shad_en_graduated_detail.html
apps/templates/users/reference_shad_en_with_courses_detail.html
apps/users/forms.py
apps/users/tests/test_certificates_of_participation.py
apps/users/views.py

fix(LMS-291): fix gender depended text

---

apps/learning/models.py
apps/learning/services/personal_assignment_service.py
apps/learning/tasks.py
apps/learning/tests/test_service_personal_assignment.py

feat(LMS-314): balanced mode backend

---

apps/learning/services/personal_assignment_service.py

fix(LMS-314): missing comma

---

lk_yandexdataschool_ru/apps/application/api/serializers.py
lk_yandexdataschool_ru/apps/application/api/tests.py
lk_yandexdataschool_ru/jinja2/lk_yandexdataschool_ru/application_form.html
lk_yandexdataschool_ru/urls.py

feat(ACADEMYDEV-550): remove ozon related things

---

.github/workflows/build.yml

fix: provenance: false

---

apps/auth/views.py
lk_yandexdataschool_ru/apps/application/api/serializers.py
lk_yandexdataschool_ru/apps/application/api/tests.py
lk_yandexdataschool_ru/apps/application/api/views.py

feat(ACADEMYDEV-553): save yandex profile information

---

lk_yandexdataschool_ru/apps/application/views.py

feat(ACADEMYDEV-588): Part 1. Musthave.

---

apps/admission/views.py
lk_yandexdataschool_ru/apps/application/api/serializers.py

feat(ACADEMYDEV-588: fix CampaignOrder validation

---

apps/templates/users/reference_shad_en_graduated_detail.html
apps/templates/users/reference_shad_en_with_courses_detail.html
apps/templates/users/reference_shad_ru_with_courses_detail.html
apps/templates/users/reference_shad_ru_without_courses_detail.html

Change signing person from Alexandra to Valentina.

Change signature in references

---

compsciclub_ru/jinja2/lms/layouts/v1_base.html
compsciclub_ru/templates/base.html
lms/jinja2/lms/layouts/v1_base.html
lms/templates/base.html

Change year in footer to 23

---

lms/jinja2/lms/courses/course_detail.html

Replace word sheet with icon

---

apps/notifications/management/commands/notify.py
apps/notifications/service.py

Убраны отправления писем, кроме набора и аутентификации

Remove non-crucial emails

---

lk_yandexdataschool_ru/apps/application/views.py
lk_yandexdataschool_ru/urls.py

Временно открываю доступ к форме подачи заявлений по секретной ссылке. Чтобы посмотреть что нужно изменить в анкете к новому набору

Enable admission form and move it to secret link

---

apps/grading/management/commands/autofail_ungraded.py
apps/grading/tests/test_commands.py
apps/projects/tests/test_commands.py

Починил команду и исправил тест.
Переместил тест и команду в другую папку, более подходящую по смыслу под функционал

аutofail_ungraded command fix

---

apps/grading/constants.py

Добавляю поддержку 20х плюсов в ЛМС

Add (make) GCC C++20 compiler

---

lms/filters.py
lms/tests.py

"Чистые" студенты (без других ролей) теперь имеют доступ только к своим веткам. То есть тем, что определены в его профилях студента. Пользователи с какой-либо не студенческой ролью видят все ветки.
Изменил тесты для актуализации функционала и добавил новые, полностью его покрывающие

Course links

---

apps/templates/admin/base_site.html
compsciclub_ru/jinja2/lms/layouts/v1_base.html
compsciclub_ru/templates/base.html
lms/jinja2/lms/layouts/v1_base.html
lms/templates/base.html

Переходим на jquery, поставляемый yastatc

Use jquery from yastatic

---

lk_yandexdataschool_ru/urls.py

Change admission form url

---

apps/courses/views/course.py
apps/learning/teaching/views/__init__.py
apps/staff/templates/staff/gradebook_list.html
apps/staff/views.py
apps/templates/learning/teaching/gradebook_list.html
lms/jinja2/lms/courses/course_detail.html
lms/jinja2/lms/study/course_list.html
lms/jinja2/lms/teaching/course_list.html

Добавляю значки полусеместровости в больше мест.

Add semi-semester icons to other places

---

apps/admission/management/commands/stage2_test_olympiad_send_emails.py
apps/admission/management/commands/stage2_test_olympiad_update_status.py
apps/admission/management/commands/stage2_test_rejected_update_status.py

Меняю скрипты, используемые после фазы контеста под новые нужды. А такжедобавляю пару новых

Update stage 2 scripts

---

apps/learning/models.py
apps/users/tests/test_models.py

Изменяю приглашение, чтобы его время жизни совпадало с временем записи на курс у привязанных курсов. В том числе с измененным временем записи, не совпадающим с общесеместровым.

Update invitation to use course enrollment time

---

apps/admission/management/commands/import_exam_results_from_csv.py
apps/admission/management/commands/stage3_exam_step4_statuses.py

Обновляю скрипты для импорта оценок ии обновления статусов после экзамена

Update exam scripts

---

apps/admission/management/commands/create_delete_interviewers.py
apps/admission/management/commands/import_interviewstreams_from_csv.py
apps/admission/management/commands/import_notes.py
apps/admission/templates/admission/interview_detail.html
apps/users/models.py

Обновляю скрипты для заливки потоков интервью и заметок абитуриентов. Добавляю новый для добавления/забирания ролей собеседующих

Interview scripts update

---

apps/admission/management/commands/create_delete_role_group.py

Script fix

---

apps/admission/filters.py
apps/admission/services.py
apps/admission/templates/admission/interview_detail.html
apps/admission/templates/admission/interview_list.html
apps/admission/tests/test_services.py
apps/admission/views.py
lms/jinja2/lms/admission/interview_invitation_list.html
lms/jinja2/lms/admission/send_interview_invitations.html

Добавляю информацию о формате собеседования для собеседующего, исправляю табличку с заметками(она разъезжалась за пределы страницы), исправляю ошибку со сбрасыванием фильтрации анкет при сохдании приглашения при переходе на другую страницу и добавляю фильтр фамилии на ту же страницу

Interview fix

---

apps/learning/signals.py
apps/learning/tests/test_student_groups.py

https://st.yandex-team.ru/DEVSHAD-44

CourseGroupModes.INVITE_AND_BRANCH fix

---

apps/templates/learning/invitation/complete_profile.html

Minor issue

---

apps/learning/management/commands/academic_discipline_from_csv.py

Update academic discipline script

---

apps/admission/management/commands/create_partner_profiles.py
apps/learning/management/commands/academic_discipline_from_csv.py

https://st.yandex-team.ru/DEVSHAD-84

Add year_of_admission to create_partner_profiles script

---

apps/admission/tests/test_services.py
apps/courses/tests/test_permissions.py
apps/learning/tests/test_enrollment.py
apps/learning/tests/test_student_groups.py
apps/users/tests/factories.py

https://st.yandex-team.ru/DEVSHAD-78

Fix StudentType in InvitedStudentFactory and wrong permission tests

---

Pipfile
Pipfile.lock

edit pipfile

---

apps/learning/models.py
apps/learning/tests/test_views.py
apps/users/tests/test_services.py
lms/jinja2/lms/courses/course_detail.html
lms/jinja2/lms/enrollment/invitation_courses.html

https://st.yandex-team.ru/DEVSHAD-106

Invitation enrollment fix

---

Makefile
apps/admission/reports.py
apps/core/management/commands/clear_scheduled_jobs.py
apps/courses/models.py
apps/courses/signals.py
apps/courses/tasks.py
apps/courses/tests/test_tasks.py
apps/grading/tasks.py
apps/users/models.py
apps/users/services.py
apps/users/tests/test_models.py
apps/users/tests/test_services.py
lk_yandexdataschool_ru/k8s/templates/queue/deployment.yaml
lms/tests.py

https://st.yandex-team.ru/DEVSHAD-100

Priority fix

---

apps/grading/tasks.py

https://st.yandex-team.ru/DEVSHAD-118

contest api monitor_submission_status_in fix

---

apps/courses/models.py
apps/courses/tests/test_models.py

https://st.yandex-team.ru/DEVSHAD-120

Remove inside semester validation

---

apps/users/admin.py

https://st.yandex-team.ru/DEVSHAD-136

Add more search fields to UserAdmin

---

apps/courses/selectors.py
apps/learning/admin.py
apps/learning/api/urls.py
apps/learning/api/views.py
apps/learning/managers.py
apps/learning/services/assignment_service.py
apps/learning/study/tests/test_misc.py
apps/learning/study/views.py
apps/learning/teaching/tests/test_views.py
apps/learning/teaching/views/assignments.py
apps/learning/tests/test_services.py
apps/staff/templates/staff/enrolees_selection_list.html
apps/users/views.py
compsciclub_ru/jinja2/lms/layouts/v1_base.html
compsciclub_ru/templates/base.html
lms/jinja2/lms/layouts/v1_base.html
lms/templates/base.html

https://st.yandex-team.ru/DEVSHAD-142

Use active student assignments, don't create unactive ones

---

apps/learning/forms.py
apps/learning/tests/test_enrollment.py
apps/learning/views/enrollment.py
apps/users/services.py

Add reason field to invitation enrollment form if ask_enrollment_reason is True for course

---

apps/learning/invitation/views.py

fix: bug invitation link checking semester

---

apps/admission/constants.py
apps/admission/reports.py
lk_yandexdataschool_ru/apps/application/views.py

DEVSHAD-229
---
[admission_minsk_2024_report_03.03.2025.xlsx](https://github.com/user-attachments/files/19055088/admission_minsk_2024_report_03.03.2025.1.xlsx)
[admission_minsk_2024_report_03.03.2025.csv](https://github.com/user-attachments/files/19055089/admission_minsk_2024_report_03.03.2025.3.csv)

feat separate utm tags in report

---

apps/learning/study/views.py
lms/jinja2/lms/study/course_list.html

https://st.yandex-team.ru/DEVSHAD-237
---

add symbols to my courses

---

apps/users/filters.py

https://st.yandex-team.ru/DEVSHAD-250
---

feat: filter site

---

apps/api/management/commands/weekly_dump_to_yandex_disk.py

fix command n+1

---

lk_yandexdataschool_ru/jinja2/lk_yandexdataschool_ru/application_form.html
lk_yandexdataschool_ru/urls.py

change titles

---

apps/admission/locale/ru/LC_MESSAGES/django.po

fix translations

---

apps/staff/forms.py
apps/staff/views/send_letters_view.py
lms/jinja2/lms/admission/applicant_list.html
locale/ru/LC_MESSAGES/django.po

https://st.yandex-team.ru/DEVSHAD-292
---

Fix  bug with status

---

apps/staff/utils.py

https://st.yandex-team.ru/DEVSHAD-297
---

fix: max len 500

---

apps/staff/utils.py

fix: max len

---

apps/admission/constants.py
apps/admission/locale/ru/LC_MESSAGES/django.po
apps/api/management/commands/monthly_dump_to_yandex_disk.py
lk_yandexdataschool_ru/k8s/templates/periodic-tasks/monthly_dump_to_yandex_disk.yaml
locale/ru/LC_MESSAGES/django.po

https://st.yandex-team.ru/DEVSHAD-284
---

add monthly dump

---

apps/learning/reports.py
apps/staff/filters.py
apps/staff/utils.py
apps/staff/views/views.py

https://st.yandex-team.ru/DEVSHAD-285
---
Props/praise - что то хорошее
Question - просто вопрос
Nit/nitpick/opinion - придирки и мелочи (не обязательно к исполнению)
Suggestion/FYI - предложения на будущее (не обязательно к исполнению в этом пр)
Convention - соглашения в команде (обязательно к исполнению, ex: человекочитаемые naming)
Blocking - ошибки, баги в исполнение и подобное (обязательно к исполнению)

Invited report

---

apps/admission/reports.py

add uid to daily dump
